launch:
  ros__parameters:
    joy: true
    image_view: false
    rviz: false

controller:
  ros__parameters:
    linear_max_vel: 0.4
    angular_max_vel: 1.0
     
data_collector:
  ros__parameters:
    image_topic: "/image_raw"
    odom_topic: "/odometry"
    cmd_vel_topic: "/cmd_vel"
    image_height: 88
    image_width: 200
    dataset_folder: "dataset"
    max_data_count: 1000000
    interval_ms: 200
    save_node_freq: 3 # [s]
    show_histogram: true