launch:
  ros__parameters:
    use_rviz: true
     
data_collector:
  ros__parameters:
    image_topic: "/image_raw"
    cmd_vel_topic: "/cmd_vel"
    image_width: 224
    image_height: 224
    output_path: "dataset.pt"
    max_data_count: 10000
