launch:
  ros__parameters:
    joy: true
    image_view: false
    rviz: false

controller:
  ros__parameters:
    linear_max_vel: 0.4
    angular_max_vel: 1.0
     
data_collector:
  ros__parameters:
    image_topic: "/image_raw"
    cmd_vel_topic: "/cmd_vel"
    image_height: 88
    image_width: 200
    log_name: "dataset.pt"
    max_data_count: 1000000
    interval_ms: 200