launch:
  ros__parameters:
    joy: true
    image_view: false
    rviz: false

controller:
  ros__parameters:
    linear_max_vel: 3.0
    angular_max_vel: 1.57

data_collector:
  ros__parameters:
    image_topic: "/image_raw"
    odom_topic: "/odometry"
    cmd_vel_topic: "/cmd_vel"
    image_height: 224
    image_width: 224
    dataset_folder: "dataset"
    interval_ms: 100
    save_node_freq: 1 # [s]
    show_histogram: true
    samples_per_shard: 1000
    enable_compression: true
    swap_rb_channels: true
