train:
  batch_size: 32          # バッチサイズ（1ステップあたりのサンプル数）
  epochs: 10              # エポック数（全データを何周するか）
  learning_rate: 0.0001   # 学習率（Adam最適化器に渡す）
  shuffle: true           # データローダのシャッフル設定（true 推奨）